[versions]
# plugins
androidGradle                       = "7.2.1"
detekt                              = "1.20.0"
junit                               = "1.8.2.0"
ksp                                 = "1.6.21-1.0.5"
ktLint                              = "10.3.0"

# production libraries
coil                                = "2.1.0"
compose                             = "1.2.0-beta02"
composeActivity                     = "1.4.0"
composeNavigation                   = "2.4.2"
composeNavigationHilt               = "1.0.0"
hilt                                = "2.42"
kotlin                              = "1.6.21"
kotlinCoroutines                    = "1.6.2"
kotlinSerializationConverter        = "0.8.0"
lifecycle                           = "2.4.1"
retrofit                            = "2.9.0"
room                                = "2.4.2"
timber                              = "5.0.1"

# test libraries
testJunit                           = "5.8.2"
testMockk                           = "1.12.4"
testTurbine                         = "0.8.0"

# android test libraries
testAndroidJunitExt                 = "1.1.3" # to prevent manifest crashes in UI tests for Android 12 (1.1.3 or higher needed)
testAndroidRunner                   = "1.4.0"


[plugins]
androidApplication                  = { id = "com.android.application", version.ref = "androidGradle" }
androidLibrary                      = { id = "com.android.library", version.ref = "androidGradle" }
detekt                              = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt                                = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
junit                               = { id = "de.mannodermaus.android-junit5", version.ref = "junit" }
kotlin                              = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt                          = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinParcelize                     = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization                 = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp                                 = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktLint                              = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktLint" }


[libraries]
# production libraries
coil                                = { module = "io.coil-kt:coil", version.ref = "coil" }
composeActivity                     = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
composeMaterial                     = { module = "androidx.compose.material:material", version.ref = "compose" }
composeNavigation                   = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
composeNavigationHilt               = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "composeNavigationHilt" }
composeTooling                      = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
hilt                                = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler                        = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
kotlinCoroutines                    = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinSerializationConverter        = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinSerializationConverter" }
lifecycleRuntime                    = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleViewModel                  = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
retrofit                            = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room                                = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler                        = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtx                             = { module = "androidx.room:room-ktx", version.ref = "room" }
timber                              = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# test libraries
testJunitApi                        = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "testJunit" }
testJunitEngine                     = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "testJunit" }
testJunitParams                     = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "testJunit" }
testKotlin                          = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
testKotlinCoroutines                = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
testMockk                           = { module = "io.mockk:mockk", version.ref = "testMockk" }
testTurbine                         = { module = "app.cash.turbine:turbine", version.ref = "testTurbine" }

# android test libraries
testAndroidCompose                  = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
testAndroidJunitExt                 = { module = "androidx.test.ext:junit", version.ref = "testAndroidJunitExt" }
testAndroidHilt                     = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
testAndroidHiltCompiler             = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
testAndroidRunner                   = { module = "androidx.test:runner", version.ref = "testAndroidRunner" }

# debug libraries
debugComposeManifest                = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }


[bundles]
# TODO: bundle dependencies on real-life module usage, not my arbitrary 'classic' partition
