[versions]
# plugins
android-gradle                      = "8.3.2"
detekt                              = "1.23.6"
detekt-compose-rules                = "0.3.15"
junit                               = "1.10.0.0"
ksp                                 = "1.9.23-1.0.20"
ktlint                              = "3.16.0"

# production libraries
coil                                = "2.6.0"
compose-bom                         = "2024.04.00"
compose-compiler                    = "1.5.11"
compose-material3                   = "1.2.1"
hilt                                = "2.51.1"
kotlin                              = "1.9.23"
kotlin-coroutines                   = "1.8.0"
kotlin-serialization                = "1.6.3"
lifecycle                           = "2.7.0"
navigation                          = "2.7.7"
navigation-hilt                     = "1.2.0"
okhttp-logging-interceptor          = "4.12.0"
retrofit                            = "2.11.0"
room                                = "2.6.1"
timber                              = "5.0.1"

# test libraries
test-junit                          = "5.10.2"
test-mockk                          = "1.13.10"
test-turbine                        = "1.1.0"

# android test libraries
test-android-baseline-profile       = "1.2.3"
test-android-compose-ui-test        = "1.6.5"
test-android-junit                  = "1.1.5"
test-android-profile-installer      = "1.3.1"
test-android-runner                 = "1.5.2"


[plugins]
android-application                 = { id = "com.android.application", version.ref = "android-gradle" }
android-library                     = { id = "com.android.library", version.ref = "android-gradle" }
android-test                        = { id = "com.android.test", version.ref = "android-gradle" }
baseline-profile                    = { id = "androidx.baselineprofile", version.ref = "test-android-baseline-profile" }
detekt                              = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt                                = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
junit                               = { id = "de.mannodermaus.android-junit5", version.ref = "junit" }
kotlin                              = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize                    = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization                = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp                                 = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint                              = { id = "org.jmailen.kotlinter", version.ref = "ktlint" }


[libraries]
# production libraries
coil                                = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-bom                         = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material3                   = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
detekt-compose-rules                = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detekt-compose-rules" }
hilt                                = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler                       = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
kotlin-coroutines                   = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-serialization                = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-serialization-converter      = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
lifecycle-runtime-compose           = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation                          = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigation-hilt                     = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "navigation-hilt" }
okhttp-logging-interceptor          = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp-logging-interceptor" }
retrofit                            = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
room                                = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler                       = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx                            = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
timber                              = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# test libraries
test-junit                          = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "test-junit" }
test-kotlin                         = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
test-kotlin-coroutines              = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
test-mockk                          = { group = "io.mockk", name = "mockk", version.ref = "test-mockk" }
test-turbine                        = { group = "app.cash.turbine", name = "turbine", version.ref = "test-turbine" }

# android test libraries
test-android-benchmark-macro        = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "test-android-baseline-profile" }
test-android-compose                = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "test-android-compose-ui-test" }
test-android-hilt                   = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
test-android-hilt-compiler          = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
test-android-junit                  = { group = "androidx.test.ext", name = "junit", version.ref = "test-android-junit" } # for @RunWith(AndroidJUnit4::class)
test-android-profile-installer      = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "test-android-profile-installer" } # for consuming baseline-prof.txt
test-android-runner                 = { group = "androidx.test", name = "runner", version.ref = "test-android-runner" }

# debug libraries
debug-compose-manifest              = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "test-android-compose-ui-test" }


[bundles]
common-test = [
    "test-junit",
    "test-kotlin",
    "test-kotlin-coroutines",
    "test-mockk",
    "test-turbine"
]
common-android-test = [
    "test-android-compose",
    "test-android-hilt",
    "test-android-runner"
]
