[versions]
# plugins
androidGradle                       = "7.2.2"
detekt                              = "1.21.0"
junit                               = "1.8.2.1"
ksp                                 = "1.7.10-1.0.6"
ktLint                              = "11.0.0"

# production libraries
coil                                = "2.2.0"
compose                             = "1.2.1"
composeAccompanist                  = "0.25.1"
composeCompiler                     = "1.3.0"
composeNavigation                   = "2.5.1"
composeNavigationHilt               = "1.0.0"
desugar                             = "1.1.8"
hilt                                = "2.43.2"
kotlin                              = "1.7.10"
kotlinCoroutines                    = "1.6.4"
kotlinSerialization                 = "1.4.0"
kotlinSerializationConverter        = "0.8.0"
lifecycle                           = "2.5.1"
material                            = "1.6.1"
okHttpLoggingInterceptor            = "4.10.0"
retrofit                            = "2.9.0"
room                                = "2.4.3"
timber                              = "5.0.1"

# test libraries
testJunit                           = "5.9.0"
testMockk                           = "1.12.7"
testTurbine                         = "0.9.0"

# android test libraries
testAndroidJunitExt                 = "1.1.3" # to prevent manifest crashes in UI tests for Android 12 (1.1.3 or higher needed)
testAndroidRunner                   = "1.4.0"


[plugins]
androidApplication                  = { id = "com.android.application", version.ref = "androidGradle" }
androidLibrary                      = { id = "com.android.library", version.ref = "androidGradle" }
detekt                              = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt                                = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
junit                               = { id = "de.mannodermaus.android-junit5", version.ref = "junit" }
kotlin                              = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt                          = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinParcelize                     = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization                 = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp                                 = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktLint                              = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktLint" }


[libraries]
# production libraries
coil                                = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
composeAccompanistSwipeRefresh      = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "composeAccompanist" }
composeMaterial                     = { module = "androidx.compose.material:material", version.ref = "compose" }
composeNavigation                   = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
composeNavigationHilt               = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "composeNavigationHilt" }
desugar                             = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
hilt                                = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler                        = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
kotlinCoroutines                    = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinSerialization                 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlinSerializationConverter        = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinSerializationConverter" }
lifecycleViewModel                  = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material                            = { module = "com.google.android.material:material", version.ref = "material" }
okHttpLoggingInterceptor            = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttpLoggingInterceptor" }
retrofit                            = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room                                = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler                        = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtx                             = { module = "androidx.room:room-ktx", version.ref = "room" }
timber                              = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# test libraries
testJunit                           = { module = "org.junit.jupiter:junit-jupiter", version.ref = "testJunit" }
testKotlin                          = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
testKotlinCoroutines                = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
testMockk                           = { module = "io.mockk:mockk", version.ref = "testMockk" }
testTurbine                         = { module = "app.cash.turbine:turbine", version.ref = "testTurbine" }

# android test libraries
testAndroidCompose                  = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
testAndroidJunitExt                 = { module = "androidx.test.ext:junit", version.ref = "testAndroidJunitExt" }
testAndroidHilt                     = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
testAndroidHiltCompiler             = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
testAndroidRunner                   = { module = "androidx.test:runner", version.ref = "testAndroidRunner" }

# debug libraries
debugComposeManifest                = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }


[bundles]
common = [
    "composeMaterial",
    "composeNavigation",
    "hilt",
    "kotlinCoroutines",
    "timber"
]

commonTest = [
    "testJunit",
    "testKotlin",
    "testKotlinCoroutines",
    "testMockk",
    "testTurbine"
]
